### ISSUE TITLE
Cache fails with certain objects containing environments

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/reproducible#298] opened 2023-04-04 14:55 UTC
Using the following from a SpaDES simulation produces simliar errors:

1. `map` objects (<https://github.com/PredictiveEcology/map>)

```r
Trying to do a deep copy (Copy) of object of class mapwhich does not appear to be a normal environment. If it can be copied like a normal environment, ignore this message; otherwise, may need to create a Copy method for this class. See ?Copy
```

Also, it appears that once this gets run with an existing cache, that cache become corrupted and subsequently trying to access the cache (e.g., `showCache` or `clearCache`) will crash the R session.

```r
library(sp)
library(raster)
library(reproducible)
library(map)

options(reproducible.useTerra = TRUE)

cwd <- getwd()
setwd(tempdir())
coords <- structure(c(-122.98, -116.1, -99.2, -106, -122.98,
                      59.9, 65.73, 63.58, 54.79, 59.9),
                    .Dim = c(5L, 2L))
Sr1 <- Polygon(coords)
Srs1 <- Polygons(list(Sr1), "s1")
StudyArea <- SpatialPolygons(list(Srs1), 1L)
crs(StudyArea) <- paste("+init=epsg:4326 +proj=longlat +datum=WGS84",
                        "+no_defs +ellps=WGS84 +towgs84=0,0,0")
StudyArea <- SpatialPolygonsDataFrame(StudyArea,
                                      data = data.frame(ID = 1, shinyLabel = "zone2"),
                                      match.ID = FALSE)

ml <- Cache({
  mapAdd(StudyArea, isStudyArea = TRUE, layerName = "Small Study Area",
         poly = TRUE, analysisGroup2 = "Small Study Area")
})
```

2. futures, e.g., when enabling SpaDES memory use functionality

```r
Trying to do a deep copy (Copy) of object of class CallrFuturewhich does not appear to be a normal environment. If it can be copied like a normal environment, ignore this message; otherwise, may need to create a Copy method for this class. See ?CopyTrying to do a deep copy (Copy) of object of class MultiprocessFuturewhich does not appear to be a normal environment. If it can be copied like a normal environment, ignore this message; otherwise, may need to create a Copy method for this class. See ?CopyTrying to do a deep copy (Copy) of object of class Futurewhich does not appear to be a normal environment. If it can be copied like a normal environment, ignore this message; otherwise, may need to create a Copy method for this class. See ?CopyTrying to do a deep copy (Copy) of object of class environmentwhich does not appear to be a normal environment. If it can be copied like a normal environment, ignore this message; otherwise, may need to create a Copy method for this class. See ?Copy
```

Unable to confirm this reprex because of https://github.com/PredictiveEcology/Require/issues/83, but setting `spades.memoryUseInterval` is enough to trigger the bug.

```r
library(SpaDES.core)

options(spades.memoryUseInterval = 0.5)

parameters <- list(
  .globals = list(stackName = "landscape", burnStats = "nPixelsBurned"),
  .progress = list(NA),
  randomLandscapes = list(nx = 100L, ny = 100L, inRAM = TRUE),
  fireSpread = list(nFires = 10L, spreadprob = 0.225, its = 1e6,
                    persistprob = 0, returnInterval = 1, startTime = 0,
                    .plotInitialTime = 0, .plotInterval = 10),
  caribouMovement = list(N = 100L, moveInterval = 1, torus = TRUE,
                         .plotInitialTime = 1, .plotInterval = 1)
)

mySim <- Cache({
  simInitAndSpades(
    times = list(start = 0.0, end = 2.0, timeunit = "year"),
    params = parameters,
    modules = list("randomLandscapes", "fireSpread", "caribouMovement"),
    objects = list(),
    paths = list(modulePath = system.file("sampleModules", package = "SpaDES.core"))
  )
})
```

**Comment by eliotmcintire** [comment] 2023-04-21 18:26
Since this isn't a reprex (I don't know which versions of those packages you are using), I am trying with the "HEAD" of each of the packages you mention. I don't get your errors: 

1. Somebody needs to make the `Copy` method for the `map` class. This should be placed in the `map` package and should do all the things necessary to make a deep copy. I do get "corrupt" `ml` object, in the sense that it becomes the `Spatial*` object, rather than the `map` class object that it is supposed to be. But this will be fixed with a `Copy` method for `ml` class.
2. The issue referenced  https://github.com/PredictiveEcology/Require/issues/83 is not longer an error due to ongoing changes in the package and has been closed.
3. The last example shown here runs fine for me.

... But I am seeing a different issue... 
1. The `reproducible` package is going to  no longer support `Spatial*` and `Raster*` classes. Nevertheless, I have added some more functionality in `fixErrorsIn` that will deal with `Spatial*` class objects. This was being triggered from within `mapAdd`. These downstream packages and code should convert to the object classes in `sf` or `terra`. THIS IS FIXED in PredictiveEcology/reproducible@terra-migration which will be shortly merged into `@development`

I am closing this and opening an issue in PredictiveEcology/map#9

**Closed by eliotmcintire** 2023-04-21 18:26 UTC
