### ISSUE TITLE
file copy is generating unnecessary copies 

### ISSUE THREAD

**Issue by ianmseddy** [PredictiveEcology/reproducible#84] opened 2018-12-07 23:41 UTC
My cache folder is filling up with identical rasters. The postprocess cache is employed correctly but the file is still copied into the cache folder. Probably something in prepareFileBackedRaster.

**Comment by CeresBarros** [comment] 2019-03-19 20:47
This is also happening to me. 
Not sure if directly related with file copy, thought. At first I attributed it to `.prepareFileBackedRaster` but not sure this is where it's happening. I'll add comments to this issue if i find anything. In the meantime, if others also have this problem let me know.

**Comment by CeresBarros** [comment] 2019-03-19 21:56
The problem seems to be multiple calls to `.prepareFileBackedRaster` from nested Cache calls inside `prepInputs `(e.g.). At the end of the `Cache` call to `postProcess`, `prepareFileBackedRaster `will already deal with the correct file naming and saving. However, this is repeated once again during the `Cache` call to `prepInputs`, which ends up duplicating the file

**Comment by eliotmcintire** [comment] 2019-09-25 02:54
I believe this is not a problem, per se. It is more an issue that multiple `Cache` calls are occurring, all with identical outputs. I am closing this as this is really a different issue.

**Closed by eliotmcintire** 2019-09-25 02:54 UTC

**Comment by CeresBarros** [comment] 2019-09-26 22:09
Can we please reopen this? I made a reproducible example that shows that `Cache` is creating multiple copies of the same raster:
```
library(SpaDES)

studyArea <- randomStudyArea(seed = 1234, size = (250^2)*100)
rawBiomassMapFilename <- file.path(tempdir(), "NFI_MODIS250m_kNN_Structure_Biomass_TotalLiveAboveGround_v0.tif")
rawBiomassMapURL <- "http://tree.pfc.forestry.ca/kNN-StructureBiomass.tar"

rawBiomassMap <- Cache(prepInputs,
                       targetFile = asPath(basename(rawBiomassMapFilename)),
                       archive = asPath(c("kNN-StructureBiomass.tar",
                                          "NFI_MODIS250m_kNN_Structure_Biomass_TotalLiveAboveGround_v0.zip")),
                       url = rawBiomassMapURL,
                       destinationPath = tempdir(),
                       studyArea = studyArea,
                       rasterToMatch = NULL,
                       maskWithRTM = FALSE,
                       useSAcrs = FALSE,   
                       method = "bilinear",
                       datatype = "INT2U",
                       filename2 = NULL,"stable",
                       cacheRepo = tempdir())

rasterToMatchLarge <- rawBiomassMap
RTMvals <- getValues(rasterToMatchLarge)
rasterToMatchLarge[!is.na(RTMvals)] <- 1

list.files(tempdir(), pattern = "rasterToMatchLarge")

rasterToMatchLarge <- Cache(writeOutputs, rasterToMatchLarge,
                            filename2 = file.path(tempdir(), "rasterToMatchLarge.tif"),
                            datatype = "INT2U", overwrite = TRUE,
                            cacheRepo = tempdir())

list.files(tempdir(), pattern = "rasterToMatchLarge")
list.files(file.path(tempdir(), "rasters"), pattern = "rasterToMatchLarge")

rasterToMatchLarge <- Cache(writeOutputs, rasterToMatchLarge,
                            filename2 = file.path(tempdir(), "rasterToMatchLarge.tif"),
                            datatype = "INT2U", overwrite = TRUE,
                            cacheRepo = tempdir())

list.files(tempdir(), pattern = "rasterToMatchLarge")
list.files(file.path(tempdir(), "rasters"), pattern = "rasterToMatchLarge")

rasterToMatchLarge <- Cache(writeOutputs, rasterToMatchLarge,
                            filename2 = file.path(tempdir(), "rasterToMatchLarge.tif"),
                            datatype = "INT2U", overwrite = TRUE,
                            cacheRepo = tempdir())

list.files(tempdir(), pattern = "rasterToMatchLarge")
list.files(file.path(tempdir(), "rasters"), pattern = "rasterToMatchLarge")
```
