### ISSUE TITLE
.reproducibleTempCacheDir

### ISSUE THREAD

**Issue by ygc2l** [PredictiveEcology/reproducible#117] opened 2019-05-21 21:52 UTC
Briefly, I need to change `.reproducibleTempCacheDir` because it doesn't exist anymore. How do I do that?

Thanks.

**Comment by eliotmcintire** [comment] 2019-05-21 22:02
It should be there if you installed the package correctly, and then load it.

If not, you can see it here:
https://github.com/PredictiveEcology/reproducible/blob/1b3ae1c0fb23926eeea0c8d97acd31075bea6823/R/zzz.R#L41

Which is currently (in development branch)
`.reproducibleTempCacheDir <- file.path(tempdir(), "reproducible", "cache")`

**Comment by ygc2l** [comment] 2019-05-22 12:42
Yeah well "should" :).

Reinstalling the package doesn't do the trick nor reinstalling R entirely...

Le mar. 21 mai 2019 18 h 02, Eliot McIntire <notifications@github.com> a
écrit :

**Comment by achubaty** [comment] 2019-05-22 14:10
if the problem is that it doesn't exist (i.e., you accidentally deleted it), then simply re-create that path.

```r
checkPath(.reproducibleTempCacheDir, create = TRUE)
```

Unless this is an actual problem with the package not creating that path in the first place, this isn't really an issue.

**Comment by ygc2l** [comment] 2019-05-22 14:27
Let's say I can't re-create that path because it was an external hard drive
connected to another machine.

What's odd is that the tempdir() used by reproducible still points to this
old path...

Le mer. 22 mai 2019 à 10:10, Alex Chubaty <notifications@github.com> a
écrit :

**Comment by achubaty** [comment] 2019-05-22 14:36
@eliotmcintire confirmed that separate R sessions are using the same temp path -- is this being set during package installation? normally this is a non-issue, except when first installed to a removable disk.

**Comment by achubaty** [comment] 2019-05-22 14:39
@eliotmcintire the path is set because that assignment does not occur in the `.onAttach`/`.onLoad`. Is this behaviour intentional?

@ygc2l try reinstalling the package to a non-removable disk to reset this path for now

**Comment by ygc2l** [comment] 2019-05-22 14:51
@achubaty, that's what I have been doing since the beginning. Also to give more info, my `.reproducibleTempCacheDir` looks like this after reinstallation:

`"D:\\temp\\RtmpCQtcOa/reproducible/cache"`

The Rtmp changes between R installations but not the `"D:\\temp"`. I am wondering is it's a machine-, or package-related problem or related to both?

**Comment by achubaty** [comment] 2019-05-22 14:55
you need to change R `tempdir` location. per `?tempdir`:

> By default, tmpdir will be the directory given by tempdir(). 
     This will be a subdirectory of the per-session temporary
     directory found by the following rule when the R session is
     started.  The environment variables ‘TMPDIR’, ‘TMP’ and ‘TEMP’
     are checked in turn and the first found which points to a
     writable directory is used: if none succeeds ‘/tmp’ is used.  The
     path should not contain spaces. Note that setting any of these
     environment variables in the R session has no effect on
     tempdir(): the per-session temporary directory is created before
     the interpreter is started.

**Comment by ygc2l** [comment] 2019-05-22 15:06
Yes, I have checked my environment variables. Not the cause. R session tempdir() is correct in the sense that it is `"C:\\Users\\...\\RtmpYBtkrM"`...

**Comment by eliotmcintire** [comment] 2019-05-22 17:18
1) It is hidden in the package environment. So, you can't get it by just typing the `.reproducibleTempCacheDir` ... i.e., you need `reproducible:::.reproducibleTempCacheDir`

**Comment by eliotmcintire** [comment] 2019-05-22 18:20
```
assignInNamespace(".reproducibleTempCacheDir", tempdir(), envir = as.environment("package:reproducible"))

**Closed by eliotmcintire** 2019-05-22 18:20 UTC

**Comment by eliotmcintire** [comment] 2019-05-22 18:58
I will be putting it into the `.onLoad`, so it gets a new `tempdir()` each time. This will be pushed to development branch.

**Comment by ygc2l** [comment] 2019-05-22 20:03
Great, thanks! That fixed it.

Also, would you consider having a maintenance branch one day?
