### ISSUE TITLE
`postProcessTerra` fails with mismatching extents, but terra::mask doesn't 

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#242] opened 2022-03-03 01:04 UTC
For some reason `postProcessTerra` is detecting mismatching extents after cropping and re-projecting. This doesn't happen when using `terra` externally -- maybe because when I do so I re-project to the final CRS first, then crop?

```
library(terra)
library(reproducible)

studyArea <- vect(randomStudyArea(size = 1e10, seed = 123))
studyAreaRas <- rasterize(studyArea, 
                          rast(extent = ext(studyArea), crs = crs(studyArea), resolution = 250))
sppAbundURL <- "https://ftp.maps.canada.ca/pub/nrcan_rncan/Forests_Foret/canada-forests-attributes_attributs-forests-canada/2001-attributes_attributs-2001/"
sppAbundance <- prepInputs(targetFile = "NFI_MODIS250m_2001_kNN_Species_Pice_Gla_v1.tif",
                           url = sppAbundURL,
                           destinationPath = tempdir()
                           fun = "terra::rast",
                           overwrite = TRUE)
sppAbundancePost <- postProcessTerra(sppAbundance, rasterToMatch = studyAreaRas)

## fails:
Mar02 16:53:46 spcsbn rasterToMatch is supplied (deprecated); assigning it to `projectTo` and `cropTo`
Mar02 16:53:46 spcsbn     cropping...
Mar02 16:53:46 spcsbn        done in 0.0329 secs
Mar02 16:53:46 spcsbn     projection of from is same as projectTo, not projecting
Mar02 16:53:46 spcsbn     masking...
Error : [mask] extents do not match
Mar02 16:53:46 spcsbn     Mask results in an error; attempting to fix `maskTo`
Error : [mask] extents do not match
Error in retry(retries = 2, silent = FALSE, exponentialDecayBase = 1,  : 
Error : [mask] extents do not match
               
Failed after 2 attempts.
Mar02 16:53:46 spcsbn     Mask is still failing after fixing `maskTo`; attempting to fix `from`
Error : [mask] extents do not match
Error : [mask] extents do not match
Error in retry(retries = 2, silent = FALSE, exponentialDecayBase = 1,  : 
Error : [mask] extents do not match
                              
Failed after 2 attempts.
Mar02 16:53:46 spcsbn     Mask is still failing after fixing `maskTo`; attempting to fix `from`
Error in retry(retries = 2, silent = FALSE, exponentialDecayBase = 1,  : 
Error in retry(retries = 2, silent = FALSE, exponentialDecayBase = 1,  : 
Error : [mask] extents do not match
                                                              
Failed after 2 attempts.
                                                              
Failed after 2 attempts.

## but this works
sppAbundancePost <- project(sppAbundance, studyAreaRas)
sppAbundancePost <- crop(sppAbundancePost, studyAreaRas)
sppAbundancePost <- mask(sppAbundancePost, studyAreaRas)

Browse[1]> sppAbundance
class       : SpatRaster 
dimensions  : 510, 512, 1  (nrow, ncol, nlyr)
resolution  : 250, 250  (x, y)
extent      : -1419239, -1291239, 6931280, 7058780  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=lcc +lat_0=0 +lon_0=-95 +lat_1=49 +lat_2=77 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : memory 
name        : NFI_MODIS250m_2001_kNN_Species_Pice_Gla_v1 
min value   :                                          0 
max value   :                                    80.5539 
Browse[1]> studyAreaRas
class       : SpatRaster 
dimensions  : 510, 512, 1  (nrow, ncol, nlyr)
resolution  : 250, 250  (x, y)
extent      : -1419239, -1291239, 6931280, 7058780  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=lcc +lat_0=0 +lon_0=-95 +lat_1=49 +lat_2=77 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source      : memory 
name        : layer 
min value   :     1 
max value   :     1 

```

**Comment by achubaty** [comment] 2022-06-21 02:15
my current workaround is to insert the following wrapper around the problematic postProcess calls:


```r
    useTerra <- getOption("reproducible.useTerra")
    options(reproducible.useTerra = FALSE)
    postProcess(...)
    options(reproducible.useTerra = useTerra)
```

**Comment by eliotmcintire** [comment] 2023-04-26 03:10
Can't reproduce this because I don't have access to `sppAbundURL`. There are a number of objects I can't access in the follow up posts either. Closing.

**Comment by CeresBarros** [comment] 2023-04-26 04:21
oops! I have now edited the first post in case you can reopen and test @eliotmcintire

**Comment by eliotmcintire** [comment] 2023-05-02 15:21
This all works now.

**Closed** 2023-05-02 15:56 UTC

**Comment by eliotmcintire** [comment] 2023-05-02 16:00
Full reprex, with masking
```
Require::Require(c("terra", "PredictiveEcology/reproducible@development", "SpaDES.tools"))

studyArea <- vect(randomStudyArea(size = 1e10, seed = 123))
studyAreaRas <- rasterize(studyArea, 
                          rast(extent = ext(studyArea), crs = crs(studyArea), resolution = 250))
sppAbundURL <- "https://ftp.maps.canada.ca/pub/nrcan_rncan/Forests_Foret/canada-forests-attributes_attributs-forests-canada/2001-attributes_attributs-2001/NFI_MODIS250m_2001_kNN_Species_Pice_Gla_v1.tif"
sppAbundance <- prepInputs(targetFile = "NFI_MODIS250m_2001_kNN_Species_Pice_Gla_v1.tif",
                           url = sppAbundURL,
                           destinationPath = tempdir(),
                           fun = "terra::rast",
                           to = studyAreaRas,
                           overwrite = TRUE)
```
