### ISSUE TITLE
wrapping prepInputs in Cache (to avoid long "digesting" times) fails

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#259] opened 2022-09-07 22:27 UTC
I'm trying to wrap a `prepInputs(..., useCache = FALSE)` call in `Cache` to avoid a very very long wait time happening during prepInputs inner `Cache(do.call, out$fun, append(list(asPath(out$targetFilePath)), args), useCache = useCache2)` -- which doesn't happen by setting `useCache2` to FALSE. 

However, this fails and I'm wondering if there's a bug/edge case here, of if this is "normal" behaviour:
```
> system.time({
+   reductedFactCD <- Cache(do.call, 
+                           what = prepInputs, 
+                           args = list(targetFile = "reducedFactorialCD.Rdat",
+                                       destinationPath = tempDir,
+                                       fun = "readRDS", 
+                                       overwrite = TRUE,
+                                       url = "https://drive.google.com/open?id=1h8StXE0vm8xyDycRomCkwIaL7wfh5Irj",
+                                       useCache = FALSE),
+                           cacheRepo = tempDir)
+ })
Running preProcess
Preparing: reducedFactorialCD.Rdat
Checking local files...
Finished checking local files.
The googledrive package is requesting access to your Google account.
Select a pre-authorised account or enter '0' to obtain a new token.
Press Esc/Ctrl + C to cancel.

1: ceresvbarros@hotmail.com

Selection: 1
  File on Google Drive is 133.7 Mb
  File on Google Drive is 133.7 Mb
  Downloading from Google Drive.
  File on Google Drive is 133.7 Mb
File downloaded:
• reducedFactorialCD.Rdat <id: 1h8StXE0vm8xyDycRomCkwIaL7wfh5Irj>
Saved locally as:
• C:/Users/cbarros/AppData/Local/Temp/RtmpUf91fO/Require/9esgiu/reducedFactorialCD.Rdat
Hardlinked version of file(s) created at: C:/Users/cbarros/AppData/Local/Temp/RtmpUf91fO/reducedFactorialCD.Rdat, which point(s) to C:/Users/cbarros/AppData/Local/Temp/RtmpUf91fO/Require/9esgiu/reducedFactorialCD.Rdat; no copy/copies made.
Checking local files...
Finished checking local files.
Appending checksums to CHECKSUMS.txt. If you see this messagePrepInputs repeatedly,
  you can specify targetFile (and optionally alsoExtract) so it knows
  what to look for.
Error in modifiedDots[[whArgs]] : 
  attempt to select less than one element in get1index
In addition: Warning message:
In formals(fun) :
 Error in modifiedDots[[whArgs]] : 
attempt to select less than one element in get1index
```

If you're curious about the "wait times" here's a bit more diagnostic code:
```
## this is the original call. It took roughly 2h in my computer on a separate R session so I couldn't  wait for an estimate for this reprex
  reductedFactCD <- prepInputs(targetFile = "reducedFactorialCD.Rdat",
                               destinationPath = tempDir,
                               fun = "readRDS",
                               overwrite = TRUE,
                               url = "https://drive.google.com/open?id=1h8StXE0vm8xyDycRomCkwIaL7wfh5Irj",
                               cacheRepo = tempDir)

## this is fast
> system.time({
+   reductedFactCD <- readRDS("C:/Users/cbarros/AppData/Local/Temp/RtmpIfSXKE/reducedFactorialCD.Rdat")
+ })
   user  system elapsed
  29.53    0.50   30.03

## so we debug that `do.call` line that is loading the obj:
Browse[2]> system.time({
+     Cache(do.call, out$fun, append(list(asPath(out$targetFilePath)),
+                                    args), useCache = useCache2)
+ })
debug at #2: Cache(do.call, out$fun, append(list(asPath(out$targetFilePath)),
    args), useCache = useCache2)
Browse[3]> c
debugging in: Cache(do.call, out$fun, append(list(asPath(out$targetFilePath)),
    args), useCache = useCache2)
debug: {
    standardGeneric("Cache")
}
Browse[3]> c
Timing stopped at: 76.12 114.8 203.1    ## had to cancel, was taking too long

## what about no-Cache?
debug at #2: do.call(out$fun, append(list(asPath(out$targetFilePath)), args))
Browse[3]>
   user  system elapsed
  30.65    0.47   37.64

Browse[2]> system.time({
+     Cache(do.call, out$fun, append(list(asPath(out$targetFilePath)),
+                                    args), useCache = FALSE)
+ })
   user  system elapsed
  29.75    0.48   30.23

## but quick = TRUE doesn't help
Browse[2]> system.time({
+     Cache(do.call, out$fun, append(list(asPath(out$targetFilePath)),
+                                    args), useCache = useCache2, quick = TRUE)
+ })
Timing stopped at: 74.6 118 193.5


## so we try passing useCache = FALSE to prepInputs, which works, but now we can't cache anything...
> system.time({
+   reductedFactCD <- prepInputs(targetFile = "reducedFactorialCD.Rdat",
+                                destinationPath = tempDir,
+                                fun = "readRDS",
+                                overwrite = TRUE,
+                                url = "https://drive.google.com/open?id=1h8StXE0vm8xyDycRomCkwIaL7wfh5Irj",
+                                cacheRepo = tempDir,
+                                useCache = FALSE)
+ })
Running preProcess
Preparing: reducedFactorialCD.Rdat
Checking local files...
Finished checking local files.
  Skipping download: reducedFactorialCD.Rdat already present
Loading object into R
   user  system elapsed
  29.76    0.56   30.33
```

**Comment by CeresBarros** [comment] 2022-09-07 22:27
and my session info:
```
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reproducible_1.2.10.9000

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.2   terra_1.6-7        remotes_2.4.2      purrr_0.3.4        lattice_0.20-45    gargle_1.2.0       vctrs_0.4.1       
 [8] generics_0.1.3     utf8_1.2.2         blob_1.2.3         rlang_1.0.4        pkgbuild_1.3.1     pillar_1.8.0       glue_1.6.2        
[15] withr_2.5.0        DBI_1.1.3          rappdirs_0.3.3     sp_1.5-0           bit64_4.0.5        lifecycle_1.0.1    raster_3.5-29     
[22] codetools_0.2-18   memoise_2.0.1      callr_3.7.2        fastmap_1.1.0      ps_1.7.1           curl_4.3.2         fansi_1.0.3       
[29] Rcpp_1.0.9         openssl_2.0.2      cachem_1.0.6       fpCompare_0.2.4    jsonlite_1.8.0     lobstr_1.1.2       fs_1.5.2          
[36] bit_4.0.4          askpass_1.1        digest_0.6.29      processx_3.7.0     dplyr_1.0.10       grid_4.2.0         rprojroot_2.0.3   
[43] cli_3.3.0          tools_4.2.0        bitops_1.0-7       magrittr_2.0.3     RCurl_1.98-1.7     RSQLite_2.2.16     tibble_3.1.8      
[50] crayon_1.5.1       pkgconfig_2.0.3    data.table_1.14.2  prettyunits_1.1.1  Require_0.1.0.9000 googledrive_2.0.0  assertthat_0.2.1  
[57] httr_1.4.4         rstudioapi_0.14    R6_2.5.1           compiler_4.2.0    
```

**Comment by eliotmcintire** [comment] 2022-09-08 00:46
Thanks for the good `reprex`. It made it quick to debug and find the cause of the problem. It was a bug in `.robustDigest` for long character vectors (which is one of the columns in the `data.table` object). Note: I am showing times using `qs` as the backend, and also `useMemoise = TRUE`
```
options(reproducible.cacheSaveFormat = "qs", reproducible.nThreads = 2)
system.time(Cache(do.call(what = prepInputs, 
                          args = list(targetFile = "reducedFactorialCD.Rdat",
                                      destinationPath = tempDir,
                                      fun = "readRDS", 
                                      overwrite = TRUE,
                                      url = "https://drive.google.com/open?id=1h8StXE0vm8xyDycRomCkwIaL7wfh5Irj",
                                      useCache = FALSE))) )
# Saving large object (cacheId: 872366697859426b) to Cache: 2.4 Gb Done!
#    user  system elapsed 
#   63.92   14.34   79.30
system.time(Cache(do.call(what = prepInputs, 
                          args = list(targetFile = "reducedFactorialCD.Rdat",
                                      destinationPath = tempDir,
                                      fun = "readRDS", 
                                      overwrite = TRUE,
                                      url = "https://drive.google.com/open?id=1h8StXE0vm8xyDycRomCkwIaL7wfh5Irj",
                                      useCache = FALSE))) )
#   ...(Object to retrieve (872366697859426b.qs) is large: 56.6 Mb)
#      loaded cached result from previous prepInputs call
#    user  system elapsed 
#   10.76    4.20    8.69 

options(reproducible.useMemoise = TRUE) # Turn on memoise --> very fast
system.time(Cache(do.call(what = prepInputs, 
                          args = list(targetFile = "reducedFactorialCD.Rdat",
                                      destinationPath = tempDir,
                                      fun = "readRDS", 
                                      overwrite = TRUE,
                                      url = "https://drive.google.com/open?id=1h8StXE0vm8xyDycRomCkwIaL7wfh5Irj",
                                      useCache = FALSE))) )
#   ...(Object to retrieve (872366697859426b.qs) is large: 56.6 Mb)
#      loaded memoised result from previous prepInputs call
#    user  system elapsed 
#    0.41    0.33    0.75  
```

**Comment by eliotmcintire** [comment] 2022-09-08 00:47
Fixed with c698c68247d38d2505597db70b5ab40397a2d648

**Closed by eliotmcintire** 2022-09-08 00:46 UTC

**Comment by CeresBarros** [comment] 2022-09-08 03:12
thanks @eliotmcintire!

**Comment by CeresBarros** [comment] 2022-09-08 03:16
What about the error related to `Cache(do.call, prepInputs, ...)` -- is that "normal" behaviour?

**Comment by eliotmcintire** [comment] 2022-09-08 03:40
That is fixed with new feature branch `reproducible@simplify`

**Comment by CeresBarros** [comment] 2022-09-08 03:42
ok thanks!
