### ISSUE TITLE
Cache retrieval times-out/fails after several attempts, but loadFromCache works

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/reproducible#188] opened 2021-01-29 22:23 UTC
this started happening today, after having worked several times (with the same cache call/object):
(the sourced script has a Cache call)
```
source("Rscripts/Data_prep/newScripts_inProg/CompileRes_allMetrics.R") ## cache id f240263cfe4a88bc
  ...(Object to retrieve (f240263cfe4a88bc.rds) is large: 708.5 Mb)
     loaded cached result from previous loadResultsMetrics call, 
Waiting for 3.4 seconds to retry; the attempt is failing
```
this, however, works:
```
loadFromCache(cacheId = "f240263cfe4a88bc")
```

**Comment by CeresBarros** [comment] 2021-01-29 22:32
Just tried with a different Cache call, and the same is happening... :/ Not sure what's going on

**Comment by eliotmcintire** [comment] 2021-02-01 21:43
Are you using `cloudCache`? That is one of the reasons why `Cache` will timeout

**Comment by CeresBarros** [comment] 2021-02-01 21:46
I am not, no. I was going to try again today (after having rebooted my PC) to see if the problem persists. Will let you know.

**Comment by eliotmcintire** [comment] 2021-02-01 21:51
Also BTW, if the message includes the line `loaded cached result from previous loadResultsMetrics call`, then it loaded. That line occurs after the object if fully loaded. So, that is probably not the cause of the hanging

**Comment by CeresBarros** [comment] 2021-02-01 22:36
But the object isn't in R after this hanging stops. So even f it's fully loaded it's not being returned by `Cache`

**Comment by eliotmcintire** [comment] 2021-02-01 23:34
I have made some changes to a different branch. It probably will solve this issue:
`https://github.com/PredictiveEcology/reproducible/tree/prepareFileBackedRewrite`
It has different underlying `digest`, so you will have to rerun everything...

**Comment by CeresBarros** [comment] 2021-02-01 23:43
Just wanted to confirm that after having rebooted my machine the problem is not resolved. I think before updating to another branch and re-running I may try to "overwrite" the Cache

**Comment by CeresBarros** [comment] 2021-02-02 00:23
Overwriting the cache "solved" the problem

**Comment by CeresBarros** [comment] 2021-02-03 18:33
This is happening again, now with Cache(..., useCache = "overwrite") (which had previously fixed it). I can pull the branch you pointed out @eliotmcintire , but I still wonder what's going on (I had the `development `branch installed, btw).
Also, just thought I'd add the end result of the consecutive tries.

```
reproducible::Cache(..., useCache = "overwrite")
Saving large object (cacheId: 7dc8a2a1052bc799) to Cache: 127.5 Mb
(...)
Waiting for 8.5 seconds to retry; the attempt is failing
Waiting for 7.8 seconds to retry; the attempt is failing
Waiting for 9 seconds to retry; the attempt is failing
Error in retry(retries = 250, exponentialDecayBase = 1.01, quote(dbAppendTable(conn,  : 
  Error : database disk image is malformed

Failed after 250 attempts.
```

**Comment by eliotmcintire** [comment] 2021-02-03 19:03
Are you out of disk space?

**Comment by CeresBarros** [comment] 2021-02-03 19:14
No.  Still have 181Gb free

**Comment by eliotmcintire** [comment] 2021-02-03 19:17
> Error in retry(retries = 250, exponentialDecayBase = 1.01, quote(dbAppendTable(conn,  : 
  Error : database disk image is malformed

Suggests a problem with the disk ...

**Comment by CeresBarros** [comment] 2021-02-03 19:19
I think you're right that it may be my disk, but it's not happening with all cache calls (same disk, different cache folders). Could this be a case of this particular cache database being corrupt of something? is there a way to rebuild it?

**Comment by eliotmcintire** [comment] 2021-03-01 04:52
This should be a different issue about `"overwrite"`. Closing here.

**Closed by eliotmcintire** 2021-03-01 04:52 UTC
