### ISSUE TITLE
postProcess tries and fails to reproject raster when crs is the same on the raster, studyArea and rasterToMatch

### ISSUE THREAD

**Issue by ilaneshaw** [PredictiveEcology/reproducible#141] opened 2020-04-06 20:00 UTC
```r
reprexDir <- tempdir()
setwd(reprexDir)

library("reproducible")
library("data.table")
library("raster")
library("LandR")
library("googledrive")
library("SpaDES.core")
library("sf") #I have version 0.8-2

publicDrive <- "https://drive.google.com/open?id=102doJZPIBTRZbhKRSYp4Egrz9YG9RCB5"
myPathProbEx <- checkPath(file.path(getwd(), "probExFolder"), create = TRUE)

drive_download(file = as_id("https://drive.google.com/open?id=102doJZPIBTRZbhKRSYp4Egrz9YG9RCB5"), #rasterFile,
               path = file.path(paste0(myPathProbEx, "testraster.tif")), overwrite = TRUE)

testRaster <- raster(file.path(paste0(myPathProbEx, "testraster.tif")))

rasterToMatch <- prepInputsLCC()

studyArea <- prepInputs(
  targetFile = "RIA_fiveTSA.shp",
  rasterToMatch = rasterToMatch,
  url = "https://drive.google.com/open?id=1907knDAglxf6IlVXSA1efuo1d_3ICh3j",
  archive = "RIA_fiveTSA.zip",
  alsoExtract = "similar",
  destinationPath = myPathProbEx, # tempdir()
  fun = "raster::shapefile",
  overwrite = TRUE
)

proRaster <- postProcess(testRaster,
                         # filename2 = NULL,
                         studyArea = studyArea, 
                         rasterToMatch = rasterToMatch,
                         destinationPath = myPathProbEx,
                         # overwrite = getOption("reproducible.overwrite", TRUE),
                         # useCache = getOption("reproducible.useCache", FALSE),
                         # useCache = "overwrite",
                         omitArgs = c("purge", "useCache")
)
#
#any(!is.na(proRaster[])) 

#plot(rasterToMatch)
#plot(proRaster, add= TRUE)
```

```
- Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64              
 system   i386, mingw32               
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Los_Angeles         
 date     2020-04-06                  

- Packages --------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.2)
 backports     1.1.6   2020-04-05 [1] CRAN (R 3.6.3)
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.3)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.2)
 devtools      2.2.2   2020-02-17 [1] CRAN (R 3.6.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.2)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
 fs            1.4.1   2020-04-04 [1] CRAN (R 3.6.3)
 glue          1.4.0   2020-04-03 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.2)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.2)
 packrat       0.5.0   2018-11-14 [1] CRAN (R 3.6.2)
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.3)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.2)
 processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.3)
 ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.2)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.2)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.2)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.2)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.2)

[1] C:/Users/RALAS6/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.3/library
```

**Comment by achubaty** [comment] 2020-04-07 15:40
same result on Windows:

```r
> proRaster
class      : RasterLayer 
dimensions : 19200, 22800, 437760000  (nrow, ncol, ncell)
resolution : 250, 250  (x, y)
extent     : -2600000, 3100000, 5700000, 10500000  (xmin, xmax, ymin, ymax)
crs        : +proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +ellps=GRS80 +units=m +no_defs 
source     : C:/Users/alexc/AppData/Local/Temp/RtmpSIACSZ/reproducible/cache/rasters/r_tmp_2020-04-07_093432_912_86559.grd 
names      : layer 
values     : 1.000001, 2  (min, max)

> compareRaster(proRaster, rasterToMatch)
[1] TRUE
```

**Comment by achubaty** [comment] 2020-04-08 20:15
Closing. unable to reproduce. Possibly idiosyncratic failures due to RAM or other hardware limitations.

**Closed by achubaty** 2020-04-08 20:15 UTC
